name: roleta
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  google_fonts: ^8.1.0
  flutter_svg: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  get_it: ^9.2.1
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mobx_codegen: ^2.7.7
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/sounds/
